server:
  port: 8089
  forward-headers-strategy: framework
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:blog}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
  application:
    name: blog-server-java

app:
  cors-origin: "*"
  uploads-dir: ${user.dir}/uploads
  jwt-secret: ${JWT_SECRET:yuandan-2026}
  jwt-expire: 604800
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler